build:
    environment:
        php:
            version: 5.4
    tests:
        override:
            -
                command: phpunit -c app/ --coverage-clover="coverage"
                coverage:
                    file: coverage
                    format: php-clover