# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.command.run.default_name: null

services:
    # Guzzle Client
    guzzle.client:
        class: GuzzleHttp\Client

    # Product Scraper
    app.scrapers.products.scraper:
        class: AppBundle\Services\Scrapers\Products\Scraper

    # Product Transformer
    app.transformers.product.transformer:
        class: AppBundle\Services\Transformers\Product\Transformer

    # Product collection transformer
    app.transformers.product_collection.transformer:
        class: AppBundle\Services\Transformers\ProductCollection\Transformer
        arguments: ["@app.transformers.product.transformer"]

    # Convert Symfony Command to a server to enable DI
    app.command.run:
        class: AppBundle\Command\AppRunCommand
        arguments: ["%app.command.run.default_name%", "@app.scrapers.products.scraper", "@app.transformers.product_collection.transformer"]
        tags:
            -  { name: console.command }
